### ISSUE TITLE
Market analyzer - Batch candle requests failing due to being rate limited 

### ISSUE THREAD

**Issue by nikspz** [hummingbot/quants-lab#13]
### Describe the bug

fail to fetch candles using Binance (market analyzer's downloading of history candle)

![image](https://github.com/user-attachments/assets/1c2d6901-88b7-4bee-b49e-dfe042bd193e)

If you set BATCH_CANDLES_REQUEST = 100 then you will have this issue
![image](https://github.com/user-attachments/assets/d5988ddf-2e8c-4e0b-9785-9e90add49330)

### Steps to reproduce bug

1. git clone https://github.com/hummingbot/quants-lab.git
2. open with VSC, add dneitor.py 
3. set FETCH_CANDLES to True
4. run all blocks one by one

Actual:
Review it stuck on FETCH_CANDLES (~1.5 hours)

**Comment by rapcmia** [comment]
fixed using local .whl
